apiVersion: v1
kind: Service
metadata:
  name: hashing-app
spec:
  type: NodePort
  selector:
    app: hashing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
